---
output_directory: generated_activity
#process activity
process_to_start: /bin/ls
process_args: ['-l']
#file activity
test_file_path: test_file
test_file_type: txt
#network activity
destination_address: 8.8.8.8
destination_port: "53"
network_data: Test message
