---
output_directory: generated_activity
# Process activity params
process_to_start: /bin/ls
process_args: ['-l']
# File activity params
test_file_path: test_file
test_file_type: txt
# Network activity params
destination_address: 8.8.8.8
destination_port: "53"
network_data: Test message
